### PR TITLE
Update with 2015 results

### PR DESCRIPTION
**Pull request by mdboom**
Once merged, this will also need to be built and pushed to the conference website here:

http://conference.scipy.org/jhepc2013

### CODE REVIEW

**Comment by scopatz** [comment]
Is there supposed to be a detailed review process? This looks good to my quick glance.

**Comment by mdboom** [comment]
I don't think there's much to review.  The prose is all from the entrants' submissions, mostly unedited except for some formatting.  I think it best to just get this up and we can fix details later if there are any...

I've been having some requests to get this posted.  Anyone know who the contact is to post this?

**Comment by scopatz** [comment]
Hi @mdboom - I am not sure who the person to build this is.  Probably @aterrel or @mandli know.

**Comment by mandli** [comment]
I haven't the foggiest.  I would guess someone from Enthought might be able to help.

**Comment by scopatz** [comment]
@jonathanrocher  or @kjordahl, do you know how this would get built and deployed?

**Comment by mdboom** [comment]
To build: it's just a sphinx project.  For deployment, I have no idea -- all I know is that there is currently this:

http://conference.scipy.org/jhepc2013

We probably want to change that to:

http://conference.scipy.org/jhepc

**Comment by mdboom** [comment]
_Ping_.  It seems this still hasn't been posted to the website.  I'm happy to help -- but I'm not even sure who the contact for that is...

**Comment by NelleV** [comment]
I think we should consider a solution easier for "us" to update.
For instance, we could create a github page.

**Comment by mdboom** [comment]
That's not a bad idea at all.  We could probably use this github repository right here.  It would still be nice to have a redirect from `scipy.org` to it, but that would only have to be done once.

**Comment by aterrel** [comment]
FWIW, @dpinte manages the scipy.org server these days. I'm sure he can help you here.

**Pull request merged**
